//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Birthdate { get; set; }
        public string RegNo { get; set; }
        public string AadharNo { get; set; }
        public string Email { get; set; }
        public string CellPhone { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
